import test from 'node:test';
import assert from 'node:assert/strict';
import {askAI,planningContext} from '../server/ai.js';
import {sampleState} from '../public/planner.js';

test('planning context excludes identity, finances, wellbeing and notes',()=>{const state=sampleState('2026-09-16');state.profile.name='Private name';state.tasks[0].notes='Private note';const context=planningContext(state),serialized=JSON.stringify(context);assert.ok(context.tasks.length);assert.ok(!serialized.includes('Private'));assert.equal(context.expenses,undefined);assert.equal(context.wellness,undefined);assert.equal(context.digital,undefined);});
test('AI requires configuration and never calls the provider without a key',async()=>{delete process.env.OPENAI_API_KEY;await assert.rejects(askAI({message:'hello',today:'2026-09-16'},()=>{throw new Error('Unexpected call');}),e=>e.status===503);});
test('AI sends bounded conversation, uses server key and reads Responses text',async()=>{process.env.OPENAI_API_KEY='test-only-not-a-real-key';const result=await askAI({message:'Explain Java',today:'2026-09-16',history:[{role:'user',content:'I am a beginner'}]},async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.ok(options.headers.Authorization.endsWith('test-only-not-a-real-key'));const payload=JSON.parse(options.body);assert.equal(payload.store,false);assert.equal(payload.input.at(-1).content,'Explain Java');assert.equal(JSON.parse(payload.input[0].content).planningRecords,null);return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:'A class is a blueprint.'}]}]}),{status:200});});assert.equal(result.answer,'A class is a blueprint.');assert.ok(!JSON.stringify(result).includes('test-only'));delete process.env.OPENAI_API_KEY;});
test('AI reports provider errors, timeouts and empty outputs without invented fallback answers',async()=>{process.env.OPENAI_API_KEY='test-only';for(const [provider,status] of [[401,502],[429,429],[500,502]])await assert.rejects(askAI({message:'hello'},async()=>new Response('{}',{status:provider})),e=>e.status===status);await assert.rejects(askAI({message:'hello'},async()=>{throw new DOMException('timeout','TimeoutError');}),e=>e.status===504);await assert.rejects(askAI({message:'hello'},async()=>new Response(JSON.stringify({output:[]}))),e=>e.status===502);delete process.env.OPENAI_API_KEY;});
