import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import http from 'node:http';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.DATA_DIR=await mkdtemp(join(tmpdir(),'orbit-ui-'));
const {default:handler}=await import('../server/handler.js');
const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const nativeFetch=globalThis.fetch;let cookie='';let aiPayload;process.env.OPENAI_API_KEY='test-only-not-a-real-key';
globalThis.fetch=async(url,options={})=>{if(url==='https://api.openai.com/v1/responses'){aiPayload=JSON.parse(options.body);return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:'Try one Java topic at a time. <script>not executable</script>'}]}]}),{status:200});}const res=await nativeFetch(new URL(url,base),{...options,headers:{...options.headers,...(cookie?{cookie}:{})}});const c=res.headers.get('set-cookie');if(c)cookie=c.split(';')[0];return res;};
const dom=new JSDOM('<div id="app"></div><div id="toast"></div><dialog id="dialog"></dialog>',{url:base});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.FormData=dom.window.FormData;
dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new dom.window.Event('close'));};
const registered=[];document.modelContext={registerTool:t=>registered.push(t)};
const wait=async fn=>{for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw new Error('UI condition timed out. '+document.querySelector('#dialog')?.textContent?.slice(-500));};
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,`Missing ${selector}`);el.click();};
const fill=(name,value)=>{const el=document.querySelector(`#dialog [name="${name}"]`);assert.ok(el,`Missing field ${name}`);el.value=value;};
const submit=async id=>{const form=document.querySelector('#'+id);assert.ok(form);form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!document.querySelector('#dialog').hasAttribute('open')||!!form.querySelector('.form-error')?.textContent);assert.equal(form.querySelector('.form-error')?.textContent||'','');};
test('web interface: create, plan, complete, habits, wellness, money, voice, and agent entry points',async()=>{
 const created=await fetch('/api?action=register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'UI Test',email:'ui@example.test',password:'ui-test-password-123'})});assert.equal(created.status,200);
 await import('../public/app.js');await wait(()=>document.body.textContent.includes('Let’s make today count'));
 click('[data-action="add-task"]');fill('title','Java assignment');fill('duration','90');fill('due','2026-12-01');await submit('task-form');assert.match(document.body.textContent,/Task saved/);
 click('[data-action="generate-plan"]');await wait(()=>document.body.textContent.includes('Java assignment'));
 click('[data-view="Tasks"]');assert.match(document.querySelector('#main').textContent,/Java assignment/);
 click('[data-action="edit-task"]');fill('title','Java assignment revised');await submit('task-form');assert.match(document.querySelector('#main').textContent,/Java assignment revised/);
 click('[data-action="complete-task"]');fill('actual','80');await submit('completion-form');assert.ok(document.querySelector('.task-row.completed'));
 click('[data-action="reopen-task"]');await wait(()=>!document.querySelector('.task-row.completed'));
 click('[data-view="Goals"]');click('[data-action="add-goal"]');fill('title','Practise DSA');await submit('goal-form');assert.match(document.querySelector('#main').textContent,/Practise DSA/);
 click('[data-view="Habits"]');click('[data-action="add-habit"]');fill('title','Read 15 minutes');await submit('habit-form');click('[data-action="toggle-habit"]');await wait(()=>document.querySelector('.habit-check.checked'));
 click('[data-view="Wellness"]');click('[data-action="log-wellness"]');fill('sleep','7');fill('water','5');await submit('wellness-form');assert.match(document.querySelector('#main').textContent,/7h/);
 click('[data-view="Money"]');click('[data-action="add-expense"]');fill('title','Lunch');fill('amount','120');await submit('expense-form');assert.match(document.querySelector('#main').textContent,/₹120/);
 click('[data-view="Digital balance"]');click('[data-action="log-digital"]');fill('screen','100');fill('distraction','30');await submit('digital-form');assert.match(document.querySelector('#main').textContent,/1h 40m/);
 click('[data-view="Planner"]');click('[data-action="add-commitment"]');fill('title','Class');await submit('commitment-form');assert.match(document.querySelector('#main').textContent,/Class/);
 for(const view of ['Insights','Integrations','Settings','Today']){click(`[data-view="${view}"]`);assert.ok(document.querySelector('#main h1'));}
 click('[data-action="voice"]');document.querySelector('#voice-command').value='Open goals';click('#voice-run');await wait(()=>document.querySelector('#main').textContent.includes('Big goals. Small steps.'));
 click('[data-action="voice"]');document.querySelector('#voice-command').value='Add task DSA tomorrow 30 minutes';click('#voice-run');await wait(()=>document.querySelector('#dialog').textContent.includes('Review before adding'));click('[data-action="save-captured"]');await wait(()=>!document.querySelector('#dialog').hasAttribute('open'));click('[data-view="Tasks"]');assert.match(document.querySelector('#main').textContent,/DSA tomorrow/);
 click('[data-view="AI assistant"]');document.querySelector('#ai-question').value='Help me study Java';document.querySelector('#ai-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>document.querySelector('.ai-message.assistant'));assert.match(document.querySelector('.ai-message.assistant').textContent,/Try one Java topic/);assert.equal(document.querySelector('.ai-message.assistant script'),null);assert.equal(JSON.parse(aiPayload.input[0].content).planningRecords,null);click('#ai-share');assert.equal(document.querySelectorAll('.ai-message').length,0);document.querySelector('#ai-question').value='Review my tasks';document.querySelector('#ai-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>document.querySelector('.ai-message.assistant'));assert.ok(JSON.parse(aiPayload.input[0].content).planningRecords.tasks.length);
 assert.equal(registered.length,2);assert.throws(()=>registered[1].execute({title:''}));assert.equal(registered[1].execute({title:'From agent'}).saved,false);assert.equal(document.querySelector('#dialog [name="title"]').value,'From agent');document.querySelector('#dialog').close();
});
test.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(process.env.DATA_DIR,{recursive:true,force:true});dom.window.close();});
